name: 🚀 Run2

on:
  pull_request:

jobs:
  run:
    name: 🚀 Run2
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run2
        shell: bash
        run: |
          python3 script.py
